### ISSUE TITLE
Wrong address

### ISSUE THREAD

**Issue by lzytniak** [Unknown22/TangoJSDemo#1]
Firefox opens with address "http://127.0.0.1:8080/", it should open with "http://127.0.0.1:8081/"
<img width="944" alt="screen shot 2017-05-04 at 23 00 48" src="https://cloud.githubusercontent.com/assets/8569463/25724820/9746bce2-311d-11e7-8f00-f0171dbc53f3.png">

**Comment by Unknown22** [comment]
Fixed. Firefox should open correct address now.
