### ISSUE TITLE
Very long time to Firefox open

### ISSUE THREAD

**Issue by lzytniak** [Unknown22/TangoJSDemo#11]
After application download all TangoJS components like: tangojs-webapp-template etc., there is no longer required access to the github (internet).
I noticed that to run tangojsdemo, without internet connection, it takes about 5-10 minutes.
Is it correct behaviour?

<img width="878" alt="screen shot 2017-05-19 at 11 09 28" src="https://cloud.githubusercontent.com/assets/8569463/26241718/04402590-3c86-11e7-975d-62bdc4c6d552.png">

**Comment by Unknown22** [comment]
It is probably how npm works and I can't find anything to do with that :/

**Comment by lzytniak** [comment]
I noticed that you are using directly system commands like:
```
npm install --save tangojs xxx
```
Maybe, it will be good to add to TODO list, to test some python libraries to deal with npm, e.g. pynpm:
https://pypi.python.org/pypi/pynpm
Maybe there is a way to solve problem in next version.

**Comment by Unknown22** [comment]
I checked this library and this is wrapper for exactly the same thing I am doing so it won't solve the problem. I didn't find any reliable lib for npm and I wanted to avoid any external library if possible to be not dependend and to avoid user from installing not necessary files.
