### ISSUE TITLE
Don't work on CentOS 7

### ISSUE THREAD

**Issue by lzytniak** [Unknown22/TangoJSDemo#4]
<img width="702" alt="screen shot 2017-05-06 at 00 08 53" src="https://cloud.githubusercontent.com/assets/8569463/25766046/6381b8b6-31f0-11e7-8140-01e77a40eb85.png">

**Comment by Unknown22** [comment]
What exactly python version was on your system? Did you have the latest repository? Cause there was a bug for a moment which caused this but it's already fixed.
_____________
![CentOS](https://cloud.githubusercontent.com/assets/10746021/25767135/4b895e1a-31f7-11e7-995d-98e4190ba3f2.png)
_____________
![CentOS](https://cloud.githubusercontent.com/assets/10746021/25767227/cc6ab934-31f7-11e7-8306-862c18035217.png)

**Comment by lzytniak** [comment]
<img width="680" alt="screen shot 2017-05-07 at 00 21 48" src="https://cloud.githubusercontent.com/assets/8569463/25776313/62b77936-32bb-11e7-9426-8a25a1ab8bcb.png">

**Comment by Unknown22** [comment]
Bug is probably fixed in latest update. Please check it now.
