### ISSUE TITLE
fatal: destination path 'tangojs-webapp-template' already exists and is not an empty directory

### ISSUE THREAD

**Issue by lzytniak** [Unknown22/TangoJSDemo#6]
<img width="862" alt="screen shot 2017-05-08 at 12 05 24" src="https://cloud.githubusercontent.com/assets/8569463/25799773/af166d6a-33e6-11e7-9f7d-1b8bf6c5d9fb.png">

**Comment by Unknown22** [comment]
It was problem with `git clone` command, when script tried to clone project to folder where project already existed. Now script is checking if project already exist and therefore decides if clone is needed.
