### ISSUE TITLE
The script hangs when "su: Authentication Failure"

### ISSUE THREAD

**Issue by lzytniak** [Unknown22/TangoJSDemo#8]
![screen shot 2017-05-09 at 15 16 55](https://cloud.githubusercontent.com/assets/8569463/25852848/0d9a3daa-34cb-11e7-80d7-a9472c452d2a.png)

**Comment by lzytniak** [comment]
![screen shot 2017-05-09 at 15 25 58](https://cloud.githubusercontent.com/assets/8569463/25853112/e0ff1788-34cb-11e7-953c-dfbf2f81a237.png)

**Comment by Unknown22** [comment]
Problem should be fixed already.
